
const imageMapping = {
    'img101.png': require('./../assets/Images/img101.png'),
    'img102.png': require('./../assets/Images/img102.png'),
    'img103.png': require('./../assets/Images/img103.png'),
    'img104.png': require('./../assets/Images/img104.png'),
    'img105.png': require('./../assets/Images/img105.png'),
    'img106.png': require('./../assets/Images/img106.png'),
    'img107.png': require('./../assets/Images/img110.png'),
    'img108.png': require('./../assets/Images/img109.png'),
    'img109.png': require('./../assets/Images/img107.png'),
    'img110.png': require('./../assets/Images/img108.png'),
    

  'img111.png': require('./../assets/Images/img111.png'),
  'img112.png': require('./../assets/Images/img112.png'),
  'img113.png': require('./../assets/Images/img113.png'),
  'img114.png': require('./../assets/Images/img114.png'),
  'img115.png': require('./../assets/Images/img115.png'),
  'img116.png': require('./../assets/Images/img116.png'),
  'img117.png': require('./../assets/Images/img117.png'),
  'img118.png': require('./../assets/Images/img118.png'),
  'img119.png': require('./../assets/Images/img119.png'),
  'img120.png': require('./../assets/Images/img120.png'),
   
  
  'img121.png': require('./../assets/Images/img121.png'),
  'img122.png': require('./../assets/Images/img122.png'),
  'img123.png': require('./../assets/Images/img123.png'),
  'img124.png': require('./../assets/Images/img124.png'),
  'img125.png': require('./../assets/Images/img125.png'),
  'img126.png': require('./../assets/Images/img126.png'),
  'img127.png': require('./../assets/Images/img127.png'),
  'img128.png': require('./../assets/Images/img128.png'),
  'img129.png': require('./../assets/Images/img129.png'),
  'img130.png': require('./../assets/Images/img130.png'),
  'img131.png': require('./../assets/Images/img131.png'),
  'img132.png': require('./../assets/Images/img132.png'),
  'img133.png': require('./../assets/Images/img133.png'),
  'img134.png': require('./../assets/Images/img134.png'),
  'img135.png': require('./../assets/Images/img135.png'),
  'img136.png': require('./../assets/Images/img136.png'),
  'img137.png': require('./../assets/Images/img137.png'),
  'img138.png': require('./../assets/Images/img138.png'),
  'img139.png': require('./../assets/Images/img139.png'),
  'img140.png': require('./../assets/Images/img140.png'),

  'img141.png': require('./../assets/Images/img141.png'),
  'img142.png': require('./../assets/Images/img142.png'),
  'img143.png': require('./../assets/Images/img143.png'),
  'img144.png': require('./../assets/Images/img144.png'),
  'img145.png': require('./../assets/Images/img145.png'),
  'img146.png': require('./../assets/Images/img146.png'),
  'img147.png': require('./../assets/Images/img147.png'),
  'img148.png': require('./../assets/Images/img148.png'),
  'img149.png': require('./../assets/Images/img149.png'),
  'img150.png': require('./../assets/Images/img150.png'),

  'img151.png': require('./../assets/Images/img151.png'),
  'img152.png': require('./../assets/Images/img152.png'),
  'img153.png': require('./../assets/Images/img153.png'),
  'img154.png': require('./../assets/Images/img154.png'),
  'img155.png': require('./../assets/Images/img155.png'),
  'img156.png': require('./../assets/Images/img156.png'),
  'img157.png': require('./../assets/Images/img157.png'),
  'img158.png': require('./../assets/Images/img158.png'),
  'img159.png': require('./../assets/Images/img159.png'),
  'img160.png': require('./../assets/Images/img160.png'),

  'img161.png': require('./../assets/Images/img161.png'),
  'img162.png': require('./../assets/Images/img162.png'),
  'img163.png': require('./../assets/Images/img163.png'),
  'img164.png': require('./../assets/Images/img164.png'),
  'img165.png': require('./../assets/Images/img165.png'),
  'img166.png': require('./../assets/Images/img166.png'),
  'img167.png': require('./../assets/Images/img167.png'),
  'img168.png': require('./../assets/Images/img168.png'),
  'img169.png': require('./../assets/Images/img169.png'),
  'img170.png': require('./../assets/Images/img170.png'),


  'img41.png': require('./../assets/Images/img41.png'),
  'img42.png': require('./../assets/Images/img42.png'),
  'img43.png': require('./../assets/Images/img43.png'),
  'img44.png': require('./../assets/Images/img44.png'),
  'img45.png': require('./../assets/Images/img45.png'),
  'img46.png': require('./../assets/Images/img46.png'),
  'img47.png': require('./../assets/Images/img47.png'),
  };
  
  export default imageMapping;
  